# Generated by Django 5.2.14 on 2026-05-26 18:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('ACEPTABLE', 'ACEPTABLE'), ('MEDIO', 'MEDIO'), ('CRITICO', 'CRITICO')], help_text='Seleccione el nivel de riesgo', max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('factor_severidad', models.FloatField(help_text='Multiplicador para el cálculo del scoring')),
            ],
            options={
                'verbose_name': 'Categoría de Riesgo',
                'verbose_name_plural': 'Categorías de Riesgo',
            },
        ),
        migrations.CreateModel(
            name='Diferido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses_plazo', models.IntegerField()),
                ('porcentaje_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('requiere_entrada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Plan Diferido',
                'verbose_name_plural': 'Planes Diferidos',
                'ordering': ['meses_plazo'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('OLLA', 'Olla Individual'), ('SET', 'Set Completo'), ('REPUESTO', 'Repuesto')], default='OLLA', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('categoria', models.CharField(choices=[('GAMA_ALTA', 'Premium / Confort'), ('GAMA_MEDIA', 'Estándar / Familiar'), ('GAMA_BAJA', 'Escencial / Económica')], help_text='Categoría o familia del producto (opcional)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TecnicaMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Reestructuración de Cuota, Llamada Persuasiva', max_length=150)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Técnica de Mejora',
                'verbose_name_plural': 'Técnicas de Mejora',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('incidencias_mora_total', models.IntegerField(default=0)),
                ('categoria_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colaboradores.categoriariesgo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='PerfilSocioeconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresos_mensuales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_dependientes', models.IntegerField(blank=True, null=True)),
                ('nivel_educativo', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_socioeconomico', to='colaboradores.cliente')),
            ],
            options={
                'verbose_name': 'Perfil Socioeconómico',
                'verbose_name_plural': 'Perfiles Socioeconómicos',
            },
        ),
        migrations.CreateModel(
            name='HistorialGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField(auto_now_add=True)),
                ('fue_exitosa', models.BooleanField(default=False, help_text='¿La técnica logró regularizar al cliente?')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mensualidad_en_mora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de la mensualidad que estaba en mora al momento de aplicar la técnica', max_digits=10)),
                ('diferido_sugerido_meses', models.PositiveIntegerField(default=0, help_text='En caso de sugerir un plan de pago a plazo, indique la cantidad de meses recomendada')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_gestiones', to='colaboradores.cliente')),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colaboradores.tecnicamejora')),
            ],
            options={
                'verbose_name': 'Historial de Gestión',
                'verbose_name_plural': 'Historiales de Gestión',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision_calculada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('numero_cuotas_pactadas', models.IntegerField(default=1, help_text='1 si es pago al contado, más de 1 si es a plazo')),
                ('valor_mensualidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('descripcion_venta', models.CharField(blank=True, help_text='Descripción breve de la venta', max_length=255, null=True)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADA', 'Pagada'), ('EN_MORA', 'En Mora')], default='PENDIENTE', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_realizadas', to='colaboradores.cliente')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to='colaboradores.vendedor')),
                ('diferido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_asociadas', to='colaboradores.diferido')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colaboradores.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='colaboradores.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
            },
        ),
    ]
