# Generated by Django 5.2.14 on 2026-05-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriariesgo',
            name='codigo',
            field=models.CharField(choices=[('ACEPTABLE', 'ACEPTABLE'), ('MEDIO', 'MEDIO'), ('CRITICO', 'CRITICO'), ('aceptable', 'ACEPTABLE'), ('medio', 'MEDIO'), ('critico', 'CRITICO')], help_text='Seleccione el nivel de riesgo', max_length=20, unique=True),
        ),
    ]
