# Generated by Django 5.2.14 on 2026-05-29 21:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilsocioeconomico',
            name='ingresos_mensuales',
        ),
        migrations.RemoveField(
            model_name='perfilsocioeconomico',
            name='nivel_educativo',
        ),
        migrations.RemoveField(
            model_name='perfilsocioeconomico',
            name='numero_dependientes',
        ),
        migrations.RemoveField(
            model_name='perfilsocioeconomico',
            name='ocupacion',
        ),
        migrations.AddField(
            model_name='perfilsocioeconomico',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('UNION_LIBRE', 'Unión Libre')], default='SOLTERO', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilsocioeconomico',
            name='gastos_fijos_estimados',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='perfilsocioeconomico',
            name='ingreso_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilsocioeconomico',
            name='nivel_estudio',
            field=models.CharField(choices=[('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('TERCER_NIVEL', 'Tercer Nivel / Grado'), ('CUARTO_NIVEL', 'Posgrado')], default='SECUNDARIA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilsocioeconomico',
            name='numero_hijos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilsocioeconomico',
            name='tiene_hijos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilsocioeconomico',
            name='tipo_trabajo',
            field=models.CharField(choices=[('DEPENDIENTE', 'Empleado Público/Privado'), ('INDEPENDIENTE', 'Comerciante / Empresario'), ('INFORMAL', 'Actividades Informales'), ('DESEMPLEADO', 'Sin Empleo Fijo')], default='DEPENDIENTE', max_length=20),
            preserve_default=False,
        ),
    ]
