# Generated by Django 5.2.14 on 2026-05-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_alter_categoriariesgo_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comision_ganada',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto exacto de comisión guardado en el momento de la venta.', max_digits=10),
        ),
    ]
