# Generated by Django 6.0.4 on 2026-04-19 20:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_reglanegocio_vendedor_venta_comisioncalculada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglanegocio',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento aplicado a las ventas (ej: 10.00 para el 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
