# Generated by Django 5.2.14 on 2026-05-08 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_alter_reglanegocio_porcentaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: ACEPTABLE, MEDIO, CRITICO', max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('factor_severidad', models.FloatField(help_text='Multiplicador para el cálculo del scoring')),
            ],
            options={
                'verbose_name': 'Categoría de Riesgo',
                'verbose_name_plural': 'Categorías de Riesgo',
            },
        ),
        migrations.CreateModel(
            name='Diferido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses_plazo', models.IntegerField()),
                ('porcentaje_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('requiere_entrada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Plan Diferido',
                'verbose_name_plural': 'Planes Diferidos',
                'ordering': ['meses_plazo'],
            },
        ),
        migrations.CreateModel(
            name='TecnicaMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Reestructuración de Cuota, Llamada Persuasiva', max_length=150)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Técnica de Mejora',
                'verbose_name_plural': 'Técnicas de Mejora',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('OLLA', 'Olla Individual'), ('SET', 'Set Completo'), ('REPUESTO', 'Repuesto')], default='OLLA', max_length=20),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('incidencias_mora_total', models.IntegerField(default=0)),
                ('categoria_riesgo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='colaboradores.categoriariesgo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='colaboradores.cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='diferido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='colaboradores.diferido'),
        ),
        migrations.CreateModel(
            name='HistorialGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField(auto_now_add=True)),
                ('fue_exitosa', models.BooleanField(default=False, help_text='¿La técnica logró regularizar al cliente?')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_gestiones', to='colaboradores.cliente')),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colaboradores.tecnicamejora')),
            ],
            options={
                'verbose_name': 'Historial de Gestión',
                'verbose_name_plural': 'Historiales de Gestión',
            },
        ),
    ]
