# Generated by Django 5.2.14 on 2026-05-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_venta_comision_ganada'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descripcion_venta',
            field=models.TextField(blank=True, help_text='Descripción de los productos vendidos', null=True),
        ),
    ]
